---
title: "Cost-effectiveness of FLW interventions"
author: "Quentin D. Read"
date: "February 20, 2020"
output: 
  pdf_document:
    toc: TRUE
---

```{r setup, include=FALSE}
# We only want to show graphs and tables.
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE) # default to not show any of the code, messages, or warnings.
trunc_ellipsis <- function(x, n) if_else(nchar(x) < n, x, paste(substr(x, 1, n), '...')) # Convenience function to cut off long labels.
```

# Summary

**What?** Building on the analysis already done for waste tracking & analytics systems, this presents our estimates of total costs and net environmental benefits for multiple food loss/waste (FLW) reduction interventions if adopted uniformly across the United States.

The interventions compared here are:

* Waste tracking and analytics
* Consumer education campaigns
* Intelligent packaging (WIP)
* Packaging size adjustment/optimization (WIP)
* Date labeling standardization (WIP)

**How?** The data on the cost of implementation are based on a combination of structured interviews with industry practitioners and a number of assumptions we made based on different sources of information. Baseline food waste rates are derived from USDA LAFA data, converted from mass units to monetary units. The monetary value of food waste averted by the intervention is estimated from the baseline waste rate and some assumptions about the percent reduction in the waste rate if the intervention is implemented. Then we use the USEEIO input-output model to get the environmental impact reduction based on the value of food production averted by the hypothetical intervention. Finally, we also use the USEEIO model to estimate the additional environmental impact generated by the intervention itself, given the value of the infrastructure and/or equipment needed to implement (also derived from the cost data). The final results are the total cost and net environmental benefit of the intervention, as well as the cost per unit reduction of a variety of environmental impacts.

**What was the result?** *include here when results are calculated*

# Changelog

* **24 Feb 2020**: first draft

# Current status

Intervention                               | Date       | Status
------------------------------------------ | ---------- | -------------------------------------------------------------------------------
waste tracking and analytics               | 24 Feb     | first version of the analysis is done
consumer education campaigns               | 24 Feb     | have costs, need to run analysis
intelligent packaging                      | 24 Feb     | have costs for some food groups; first decide how to get costs for fresh meat then run analysis
packaging size adjustment                  | 24 Feb     | do not yet have costs
date labeling standardization              | 24 Feb     | have costs, need to run analysis

\newpage

# Methods outline

For each intervention, we need to do the following:

1. Model the costs using various assumptions. In some cases this is based on cost models provided by the FDA.
2. If necessary, convert one-time costs to annual costs, and convert all costs to the same base year (2012) so that costs are comparable across interventions.
3. Determine which categories of final demand will be affected by the intervention. For the "demand side" effects, this is relatively simple since it is just the final demand for affected food products by consumers. For the "supply side" effects the process is a little bit more involved: first we need to identify which industries are involved in implementing the intervention and then find the subset of their food purchases that would be affected by the intervention, across all affected food categories within each industry.
4. Determine which categories of final demand will be affected by the additional infrastructure or equipment needed to implement the intervention.
4. Use QFAHPD data to convert the relevant monetary flows to mass flows.
5. Use LAFA data to find the baseline waste rate in mass units for each of the relevant mass flows.
6. Use assumptions about waste rate reduction from the intervention to determine how much waste is reduced by mass.
7. Convert this reduced waste number back to monetary units.
7. Use the USEEIO 2012 model to find the environmental impact associated with this averted food waste.
8. Use the USEEIO 2012 model to find the environmental impact associated with equipment that must be purchased to implement the intervention, which will offset some of the environmental benefit.
8. Compare the net impact averted (environmental benefit) with the annual cost of intervention (using the analysis done by Mary and multiplied by the number of establishments).
9. Repeat this analysis for different values within the upper and lower bounds of our assumptions, as an uncertainty analysis to see how much the results are affected by different assumptions.

\newpage

# Analysis and results by intervention

## Waste tracking and analytics

See the detailed results in `waste_tracking_analytics.pdf` and `wastetracking_by_industry.pdf`.

**Add high-level results here.**

## Consumer education campaigns

## Date labeling standardization

```{rd}

```


## Packaging adjustments

\newpage

# Comparison of interventions

With total cost, total impact averted, and cost-effectiveness results for each intervention, we can make quantitative comparisons among them.