# WTA (Leanpath style) analysis separated out by industry
# QDR / FWE / 20 Feb 2020

# In the original WTA cost-effectiveness analysis, all possible industries were summed up.
# Because not all industries might be equally likely to adopt the intervention, it's better to do the analysis separately for each one.
# We can always add up the totals after the fact.

# Base this off wastetracking_analysis_clean.R

# Run wastetracking_analysis_clean.R through line 342 (20 Feb version)


# Impact averted by industry ----------------------------------------------


# Then run USEEIO on each column of food_U (baseline) and food_U - food_U_postintervention (averted amount)

if (!is_local) use_python('/usr/bin/python3')
source_python(file.path(fp_github, 'fwe/USEEIO/eeio_lcia.py'))

# Match row names of food_U with longer codes that eeio_lcia() will recognize
demand_codes <- as.list(all_codes$sector_desc_drc[match(rownames(food_U), all_codes$sector_code_uppercase)])

# Use map to execute the function on each column of food_U (a list) and food_U - food_U_postintervention
# 20 industries each separately.
eeio_wta_baseline_byindustry <- map(food_U, ~ eeio_lcia('USEEIO2012', as.list(. * 1e6), demand_codes)) 
eeio_wta_averted_byindustry <- map(food_U - food_U_postintervention, ~ eeio_lcia('USEEIO2012', as.list(. * 1e6), demand_codes)) 

# Combine into a data frame
eeio_dat_byindustry <- establishments_affected %>%
  ungroup %>% 
  filter(use) %>% 
  select(-use) %>%
  mutate(category = map(eeio_wta_baseline_byindustry, row.names),
         baseline = map(eeio_wta_baseline_byindustry, 1),
         impact_averted = map(eeio_wta_averted_byindustry, 1)) %>%
  unnest(cols = c(category, baseline, impact_averted))

# Impact generated by intervention, by industry ---------------------------

# Number of establishments that need to adopt intervention, multiplied by upper and lower bounds of equipment cost per establishment
equipment_cost_byindustry <- establishments_affected %>% 
  filter(use) %>%
  mutate(equipment_cost_lower = establishments * equipment_costs['lower'],
         equipment_cost_upper = establishments * equipment_costs['upper'])

# The three potential BEA industry codes to assign costs of equipment are:
# computer manufacturing, computer monitor and peripheral manufacturing, and the other machinery category which includes industrial and retail scales
industries_offset <- c('334111', '33411A', '33399A')

# Find the full names of the codes for the offsetting industries
industries_offset_codes <- all_codes$sector_desc_drc[match(industries_offset, all_codes$sector_code_uppercase)]


# Use the upper and lower bounds from the industries, and the upper and lower bounds for total cost, to get an upper and lower bound for the impact that is offset
# For each one, 20 costs * 3 offsetting industries
eeio_offsets_lower_byindustry <- map(equipment_cost_byindustry$equipment_cost_lower, 
                                     function(x) map(industries_offset_codes, ~ eeio_lcia('USEEIO2012', list(x), list(.))))
eeio_offsets_upper_byindustry <- map(equipment_cost_byindustry$equipment_cost_upper, 
                                     function(x) map(industries_offset_codes, ~ eeio_lcia('USEEIO2012', list(x), list(.))))                          

# Within each list element, find the extreme value among the 3 offset industries
eeio_offsets_lower_byindustry_combined <- map(eeio_offsets_lower_byindustry, ~ apply(do.call(cbind, .), 1, min))
eeio_offsets_upper_byindustry_combined <- map(eeio_offsets_upper_byindustry, ~ apply(do.call(cbind, .), 1, max))

# Combine the results into a single data frame using list columns
eeio_offsets_range_byindustry <- equipment_cost_byindustry %>%
  ungroup %>%
  select(-use) %>%
  mutate(category = map(eeio_offsets_lower_byindustry_combined, names),
         offset_lower = eeio_offsets_lower_byindustry_combined,
         offset_upper = eeio_offsets_upper_byindustry_combined) %>%
  unnest(cols = c(category, offset_lower, offset_upper))


# Cost of implementation, by industry -------------------------------------

# Meanwhile, combine offsets and original data

eeio_dat_byindustry_withoffset <- eeio_dat_byindustry %>%
  left_join(eeio_offsets_range_byindustry)

# Combine everything
final_result_byindustry <- eeio_dat_byindustry_withoffset %>%
  mutate(percent_averted = signif(100 * impact_averted/baseline, 2),
         net_impact_averted_lower = impact_averted - offset_upper,
         net_impact_averted_upper = impact_averted - offset_lower,
         net_percent_averted_lower = 100 * net_impact_averted_lower/baseline,
         net_percent_averted_upper = 100 * net_impact_averted_upper/baseline) %>%
  filter(grepl('enrg|eutr|gcc|land|watr', category)) %>%
  mutate(baseline = baseline * c(1e-9, 1e-6, 1e-9, 1e-10, 1e-9),
         impact_averted = impact_averted * c(1e-9, 1e-6, 1e-9, 1e-10, 1e-9),
         category = rep(c('energy (PJ)', 'eutrophication (kT N)', 'greenhouse gas (MT CO2)', 'land (Mha)', 'water (km3)'), nrow(.)/5),
         total_cost_lower = cost_range['lower'] * establishments,
         total_cost_upper = cost_range['upper'] * establishments,
         cost_per_reduction_lower = total_cost_lower / net_impact_averted_upper,
         cost_per_reduction_upper = total_cost_upper / net_impact_averted_lower,
         net_impact_averted_lower = net_impact_averted_lower * c(1e-9, 1e-6, 1e-9, 1e-10, 1e-9),
         net_impact_averted_upper = net_impact_averted_upper * c(1e-9, 1e-6, 1e-9, 1e-10, 1e-9)
         )

final_result_byindustry_display <- final_result_byindustry %>%
  select(sector, BEA_Title, category, cost_per_reduction_lower, cost_per_reduction_upper) %>%
  mutate(category = rep(c('energy ($/MJ)', 'eutrophication ($/kg N)', 'greenhouse gas ($/kg CO2)', 'land ($/m2)', 'water ($/m3)'), nrow(.)/5))

final_result_byindustry_display %>%
  filter(grepl('greenhouse',category), !grepl('Air', BEA_Title)) %>%
  arrange(cost_per_reduction_lower) %>%
  print(n = nrow(.))


# Write output ------------------------------------------------------------

write_csv(eeio_dat_byindustry_withoffset, file.path(fp, 'scenario_results/interventions/eeio_wta_byindustry_all.csv'))
write_csv(final_result_byindustry, file.path(fp, 'scenario_results/interventions/eeio_wta_byindustry_5categories_processed.csv'))


# Draw figures ------------------------------------------------------------

trunc_ellipsis <- function(x, n) if_else(nchar(x) < n, x, paste(substr(x, 1, n), '...'))

impact_dat <- final_result_byindustry %>%
  filter(!grepl('Air', BEA_Title)) %>%
  select(sector, BEA_Title, category, baseline, net_impact_averted_lower, net_impact_averted_upper) %>%
  mutate(net_impact_averted_mean = (net_impact_averted_upper + net_impact_averted_lower)/2) 

costper_dat <-  final_result_byindustry %>%
  filter(!grepl('Air', BEA_Title)) %>%
  select(sector, BEA_Title, category, cost_per_reduction_lower, cost_per_reduction_upper) %>%
  mutate(cost_per_reduction_mean = (cost_per_reduction_lower + cost_per_reduction_upper)/2) 

# GHG: impact reduction vs baseline
ggplot(impact_dat %>% mutate(BEA_Title = trunc_ellipsis(BEA_Title, 30)) %>% filter(grepl('greenhouse', category)), 
       aes(x = BEA_Title)) +
  geom_col(aes(y = baseline), alpha = 0.5) +
  geom_col(aes(y = baseline - net_impact_averted_mean)) +
  geom_errorbar(aes(ymin = baseline - net_impact_averted_upper, ymax = baseline - net_impact_averted_lower), width = 0.1, color = 'white') +
  facet_grid(sector ~ ., scales = 'free') +
  scale_y_continuous(name = 'Greenhouse gas emission potential (MT CO2 eq.)', expand = expand_scale(mult = c(0, 0.1))) +
  coord_flip() +
  theme_bw() +
  theme(panel.grid.major.y = element_blank(),
        panel.grid.minor.x = element_blank(),
        strip.background = element_blank()) 

# GHG: cost per reduction
ggplot(costper_dat %>% mutate(BEA_Title = trunc_ellipsis(BEA_Title, 30)) %>% filter(grepl('greenhouse', category)), 
       aes(x = BEA_Title)) +
  geom_errorbar(aes(ymin = cost_per_reduction_lower, ymax = cost_per_reduction_upper), width = 0.1) +
  facet_grid(sector ~ ., scales = 'free') +
  scale_y_continuous(name = 'Cost per 1 kg reduction', expand = expand_scale(mult = c(0, 0.1)), labels = scales::dollar) +
  coord_flip() +
  theme_bw() +
  theme(panel.grid.major.y = element_blank(),
        panel.grid.minor.x = element_blank(),
        strip.background = element_blank()) 

# Figures for all categories

impact_figs <- impact_dat %>%
  mutate(BEA_Title = trunc_ellipsis(BEA_Title, 30)) %>%
  group_by(category) %>%
  group_map(~ ggplot(., aes(x = BEA_Title)) +
                 geom_col(aes(y = baseline), alpha = 0.5) +
                 geom_col(aes(y = baseline - net_impact_averted_mean)) +
                 geom_errorbar(aes(ymin = baseline - net_impact_averted_upper, ymax = baseline - net_impact_averted_lower), width = 0.1, color = 'white') +
                 facet_grid(sector ~ ., scales = 'free') +
                 labs(x = 'industry') +
                 scale_y_continuous(name = .$category[1], expand = expand_scale(mult = c(0, 0.1))) +
                 coord_flip() +
                 theme_bw() +
                 theme(panel.grid.major.y = element_blank(),
                       panel.grid.minor.x = element_blank(),
                       strip.background = element_blank()), 
            keep = TRUE )

# They are all the same so we don't really need to show them all

# Cost figures for all categories, rearranged to show order.
cost_figs <- costper_dat %>%
  mutate(BEA_Title = trunc_ellipsis(BEA_Title, 30),
         category = rep(c('energy ($/MJ)', 'eutrophication ($/kg N)', 'greenhouse gas ($/kg CO2)', 'land ($/m2)', 'water ($/m3)'), nrow(.)/5)) %>%
  group_by(category) %>%
  group_map(function(dat, ...) 
    dat %>% arrange(sector, -cost_per_reduction_mean) %>%
      mutate(BEA_Title = factor(BEA_Title, levels = unique(BEA_Title))) %>%
      ggplot(aes(x = BEA_Title)) +
      geom_point(aes(y = cost_per_reduction_mean), size = 3) +
      geom_errorbar(aes(ymin = cost_per_reduction_lower, ymax = cost_per_reduction_upper), width = 0.1) +
      facet_grid(sector ~ ., scales = 'free') +
      labs(x = 'industry') +
      scale_y_continuous(name = .$category[1], expand = expand_scale(mult = c(0, 0.1)), labels = scales::dollar) +
      coord_flip() +
      theme_bw() +
      theme(panel.grid.major.y = element_blank(),
            panel.grid.minor.x = element_blank(),
            strip.background = element_blank()),
    keep = TRUE )

# arrange(sector, cost_per_reduction_mean) %>%
#mutate(BEA_Title = factor(BEA_Title, levels = unique(BEA_Title))) %>%
#%>% arrange(sector, cost_per_reduction_mean) %>% mutate(BEA_Title = factor(BEA_Title, levels = unique(BEA_Title)))